### ISSUE TITLE
 Cannot load json data: file does not exist at %s' % self._path)

### ISSUE THREAD

**Issue by xiaomingjie** [jackd/template_ffd#3]
It's me again..
I've trained successfully and next step is to get evaluation results.

After tpying this
`scripts/infer.py plane`
a plane.hdf5 file is generated in `inference/_inferences/predictions`, which means so far so good.

But when I type in the next line
`scripts/chamfer.py`
The error occurs.

```
File "template_ffd/scripts/chamfer.py", line 35, in <module>
    args.overwrite)
  File "template_ffd/scripts/chamfer.py", line 15, in create_and_report
    chamfer.report_chamfer_average(**kwargs)
  File "/media/tree/data1/projects/data_prepare/template_ffd/eval/chamfer.py", line 127, in report_chamfer_average
    with manager.get_saving_dataset('r') as ds:
  File "/media/tree/data1/projects/data_prepare/dids/core.py", line 105, in __enter__
    self.open()
  File "/media/tree/data1/projects/data_prepare/dids/core.py", line 136, in open
    self.open_connection(self)
  File "/media/tree/data1/projects/data_prepare/dids/core.py", line 122, in open_connection
    self._open_resource()
  File "/media/tree/data1/projects/data_prepare/dids/file_io/json_dataset.py", line 20, in _open_resource
    'Cannot load json data: file does not exist at %s' % self._path)
```

I checked in `eval/_eval/chamfer/presampled/1024` and it is an empty folder. I suppose that it should be a json here. (But I can't find what the json is?)

Is there any other operations between this two scripts that you forgot to mention?

**Comment by jackd** [comment]
Nope, you're correct, I was just trying to be too smart for my own good while I was cleaning up the code before uploading :). I've pushed some more changes that should fix this.

Thanks for your assistance debugging. Finding issues with data saving pipelines are a pain since running the whole process from start to finish isn't something that happens a lot (since I'd have to delete all the existing data to make sure, and then regenerate, which takes time).

**Comment by seanmj** [comment]
Sorry about that I am still stuck here.
`eval/_eval/chamfer/presampled/1024` still has no json file.
I have look into dids, and change some small bug like some path errors. But still don't find where and what the json is..

**Comment by jackd** [comment]
Sorry. Repull and take 3?

**Comment by xiaomingjie** [comment]
It works!
Sorry about that I can't fix these issues alone which takes your time.
It seems that I have gone through the whole pipeline from image to 3D model and evaluation.
Thanks for your help and I will keep looking into your amazing job for learning more details!

**Comment by jackd** [comment]
All good. You've followed the instructions, so it -should- work. The fact it doesn't is my fault... but it's faster for me to fix issues as they arise for small projects like this than write battle-hardened code first time around :).

**Comment by xiaomingjie** [comment]
Oh, I have some other issues that already solved which I wasn't mentioned.
1. You should add `git clone https://github.com/jackd/tf_nearest_neighbour.git` in **Getting Started**
2. `model/params` folder doesn't exist at first. But you assumed it existed in `paper/create_paper_params.py` line 43.

Maybe there will be more questions coming to you when I look into your paper and code lol...
if it happens, I may list my confusions then email you. Still hope that won't let you be bored with me..

**Comment by jackd** [comment]
Thanks, and fixed :). Always happy to know about bugs - so long as you don't expect an immediate fix. I'll do what I can, but if I'm snowed under with other things it might take me a little while to get to it.
